//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinica.DOLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETA
    {
        public decimal ID_BOLETA { get; set; }
        public System.DateTime FECHA_BOLETA { get; set; }
        public decimal VALOR_BOLETA { get; set; }
        public Nullable<decimal> ID_MEDIO_PAGO { get; set; }
        public Nullable<decimal> ID_SERVICIO { get; set; }
        public Nullable<decimal> ID_CLIENTE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual MEDIO_PAGO MEDIO_PAGO { get; set; }
        public virtual SERVICIO SERVICIO { get; set; }
    }
}
