//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinica.DOLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.BOLETA = new HashSet<BOLETA>();
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public decimal ID_CLIENTE { get; set; }
        public string NOM_CLIENTE { get; set; }
        public string APE_CLIENTE { get; set; }
        public string RUT_CLIENTE { get; set; }
        public string DIRE_CLIENTE { get; set; }
        public string FONO_CLIENTE { get; set; }
        public string MAIL_CLIENTE { get; set; }
        public string PASSWORD_CLIENTE { get; set; }
        public decimal ID_SIT_ECO { get; set; }
        public string SUELDO_CLIENTE { get; set; }
    
        public virtual ICollection<BOLETA> BOLETA { get; set; }
        public virtual SITUACION_ECONOMICA SITUACION_ECONOMICA { get; set; }
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
