//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinica.DOLC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicaEntityes : DbContext
    {
        public ClinicaEntityes()
            : base("name=ClinicaEntityes")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BOLETA> BOLETA { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<DOCTOR> DOCTOR { get; set; }
        public DbSet<EMPLEADO> EMPLEADO { get; set; }
        public DbSet<INSUMO> INSUMO { get; set; }
        public DbSet<MEDIO_PAGO> MEDIO_PAGO { get; set; }
        public DbSet<PEDIDO_INSUMO> PEDIDO_INSUMO { get; set; }
        public DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public DbSet<RESERVA> RESERVA { get; set; }
        public DbSet<SERVICIO> SERVICIO { get; set; }
        public DbSet<SITUACION_ECONOMICA> SITUACION_ECONOMICA { get; set; }
        public DbSet<TIPO_FAMILIA> TIPO_FAMILIA { get; set; }
        public DbSet<TIPO_INSUMO> TIPO_INSUMO { get; set; }
        public DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public DbSet<CONTROL> CONTROL { get; set; }
    }
}
