//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinica.DOLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTOR
    {
        public DOCTOR()
        {
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public decimal ID_DOC { get; set; }
        public string NOM_DOC { get; set; }
        public string APE_DOC { get; set; }
        public string RUT_DOC { get; set; }
        public string FONO_DOC { get; set; }
        public string MAIL_DOC { get; set; }
        public string DIRE_DOC { get; set; }
        public Nullable<decimal> ID_TIPO_USUARIO { get; set; }
    
        public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
