//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinica.DOLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public decimal ID_EMP { get; set; }
        public string NOM_EMP { get; set; }
        public string APE_EMP { get; set; }
        public string RUT_EMP { get; set; }
        public string FONO_EMP { get; set; }
        public string DIRE_EMP { get; set; }
        public string MAIL_EMP { get; set; }
        public Nullable<decimal> ID_TIPO_USUARIO { get; set; }
        public string PASS_EMP { get; set; }
    
        public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
    }
}
