//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinica.DOLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSUMO
    {
        public INSUMO()
        {
            this.PEDIDO_INSUMO = new HashSet<PEDIDO_INSUMO>();
        }
    
        public decimal ID_INSUMO { get; set; }
        public string NOM_INSUMO { get; set; }
        public Nullable<decimal> ID_TIPO_INSUMO { get; set; }
        public Nullable<decimal> ID_TIPO_FAMILIA { get; set; }
        public decimal STOCK { get; set; }
        public decimal PRECIO_COMPRA { get; set; }
    
        public virtual TIPO_FAMILIA TIPO_FAMILIA { get; set; }
        public virtual TIPO_INSUMO TIPO_INSUMO { get; set; }
        public virtual ICollection<PEDIDO_INSUMO> PEDIDO_INSUMO { get; set; }
    }
}
