//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinica.DOLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDIO_PAGO
    {
        public MEDIO_PAGO()
        {
            this.BOLETA = new HashSet<BOLETA>();
        }
    
        public decimal ID_MEDIO_PAGO { get; set; }
        public string NOM_MEDIO_PAGO { get; set; }
    
        public virtual ICollection<BOLETA> BOLETA { get; set; }
    }
}
