//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinica.DOLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_INSUMO
    {
        public decimal ID_PEDIDO { get; set; }
        public decimal CANTIDAD { get; set; }
        public string ESTADO { get; set; }
        public Nullable<decimal> ID_PROVEEDOR { get; set; }
        public Nullable<decimal> ID_INSUMO { get; set; }
        public string NOM_INSUMO { get; set; }
    
        public virtual INSUMO INSUMO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
