//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinica.DOLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public PROVEEDOR()
        {
            this.PEDIDO_INSUMO = new HashSet<PEDIDO_INSUMO>();
        }
    
        public decimal ID_PROVEEDOR { get; set; }
        public string RUT_PROVEEDOR { get; set; }
        public string NOM_PROVEEDOR { get; set; }
        public string FONO_PROVEEDOR { get; set; }
        public string DIRE_PROVEEDOR { get; set; }
        public string MAIL_PROVEEDOR { get; set; }
    
        public virtual ICollection<PEDIDO_INSUMO> PEDIDO_INSUMO { get; set; }
    }
}
