//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinica.DOLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public decimal ID_RESERVA { get; set; }
        public string FECHA_HORA_RESERVA { get; set; }
        public Nullable<decimal> ID_DOC { get; set; }
        public Nullable<decimal> ID_CLIENTE { get; set; }
        public Nullable<decimal> ID_SERVICIO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual DOCTOR DOCTOR { get; set; }
        public virtual SERVICIO SERVICIO { get; set; }
    }
}
