//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinica.DOLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO
    {
        public SERVICIO()
        {
            this.BOLETA = new HashSet<BOLETA>();
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public decimal ID_SERVICIO { get; set; }
        public string NOM_SERVICIO { get; set; }
        public string DESCRIPCION_SERVICIO { get; set; }
        public decimal VALOR_SERVICIO { get; set; }
    
        public virtual ICollection<BOLETA> BOLETA { get; set; }
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
