//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinica.DOLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SITUACION_ECONOMICA
    {
        public SITUACION_ECONOMICA()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
        }
    
        public decimal ID_SIT_ECO { get; set; }
        public string AFP { get; set; }
    
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
    }
}
