//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinica.DOLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_INSUMO
    {
        public TIPO_INSUMO()
        {
            this.INSUMO = new HashSet<INSUMO>();
        }
    
        public decimal ID_TIPO_INSUMO { get; set; }
        public string NOM_TIPO_INSUMO { get; set; }
    
        public virtual ICollection<INSUMO> INSUMO { get; set; }
    }
}
